// Generated by CoffeeScript 1.6.2
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

__Model.Asignature = (function(_super) {
  __extends(Asignature, _super);

  function Asignature() {
    _ref = Asignature.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Asignature.fields("name", "semester");

  Asignature.prototype.validate = function() {
    if (!this.name) {
      return "Nombre de la materia es requerido";
    }
  };

  return Asignature;

})(Monocle.Model);
