// Generated by CoffeeScript 1.6.3
var AsignatureCtrl,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AsignatureCtrl = (function(_super) {
  __extends(AsignatureCtrl, _super);

  AsignatureCtrl.prototype.elements = {
    "#txtMateria": "asignatura",
    "#txtSemestre": "semestre"
  };

  AsignatureCtrl.prototype.events = {
    "tap a[data-action=save]": "onSave"
  };

  function AsignatureCtrl() {
    this.onError = __bind(this.onError, this);
    AsignatureCtrl.__super__.constructor.apply(this, arguments);
    __Model.Asignature.bind("error", this.onError);
  }

  AsignatureCtrl.prototype.onError = function() {
    return Lungo.Notification.error(arguments, "user", "remove-circle", 3);
  };

  AsignatureCtrl.prototype.onSave = function() {
    var Asignature, asignature;
    if (this.asignatura.val() && this.semestre.val()) {
      Lungo.Notification.show()();
      __Model.Asignature.create({
        name: this.asignatura.val(),
        semester: this.semestre.val()
      });
      Asignature = Parse.Object.extend("Asignature");
      asignature = new Asignature();
      asignature.set('name', this.asignatura.val());
      asignature.set('semester', this.semestre.val());
      asignature.setACL(new Parse.ACL(Parse.User.current()));
      asignature.save().then(function(result) {
        return Lungo.Router.article("main", "art_main");
      }, function(error) {
        return Lungo.Notification.error(error.message, "user", "remove-circle", 3);
      });
      this.asignatura.val("");
      return this.semestre.val("");
    } else {
      return Lungo.Notification.error("Por favor llene todos los campos", "Para guardar una nueva asignatura necesitas llenar todos los campos correctamente", "remove-circle", 5);
    }
  };

  return AsignatureCtrl;

})(Monocle.Controller);

__Controller.Asignature = new AsignatureCtrl("article#art_anotherAsignature");
