// Generated by CoffeeScript 1.6.3
var LoginCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LoginCtrl = (function(_super) {
  __extends(LoginCtrl, _super);

  function LoginCtrl() {
    _ref = LoginCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  LoginCtrl.prototype.elements = {
    "#txtUser": "user",
    "#txtPassword": "password"
  };

  LoginCtrl.prototype.events = {
    "tap a[data-action=login]": "onLogin",
    "tap a[data-action=singup]": "onSingup"
  };

  LoginCtrl.prototype.initialize = function() {
    if (Parse.User.current()) {
      return __Controller.Main.initialize();
    }
  };

  LoginCtrl.prototype.onLogin = function(e) {
    if (this.user.val() && this.password.val()) {
      Lungo.Notification.show();
      Parse.User.logIn(this.user.val(), this.password.val()).then(function(result) {
        return Lungo.Router.section("main");
      }, function(error) {
        return Lungo.Notification.error(error.message, "user", "user", 3);
      });
      this.password.val("");
      this.user.val("");
      return Lungo.Notification.hide();
    } else {
      return Lungo.Notification.error("Por favor llene todos los campos", "Para acceder necesitas llenar todos los campos correctamente", "warning-sign", 5);
    }
  };

  LoginCtrl.prototype.onSingup = function() {
    var user,
      _this = this;
    user = new Parse.User();
    user.set("username", this.user.val());
    user.set("password", this.password.val());
    user.set("lat", '1111');
    user.set("lon", '2222');
    return user.signUp().then(function(object, error) {
      if (error) {
        return Lungo.Notification.error(error.message, "user", "user", 3);
      } else {
        _this.user.val("");
        _this.email.val("");
        _this.password.val("");
        return Lungo.Router.back();
      }
    });
  };

  return LoginCtrl;

})(Monocle.Controller);

Lungo.ready(function() {
  __Controller.Login = new LoginCtrl("section#login");
  return __Controller.Login.initialize();
});
