// Generated by CoffeeScript 1.6.3
var MainCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

MainCtrl = (function(_super) {
  __extends(MainCtrl, _super);

  function MainCtrl() {
    _ref = MainCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  MainCtrl.prototype.events = {
    "tap a[data-action=locate]": "onLocate",
    "tap a[data-action=food]": "onfood"
  };

  MainCtrl.prototype.initialize = function() {
    var latlng, map, mapOptions, marker;
    Lungo.Notification.show();
    latlng = new google.maps.LatLng(10.99461, -74.790997);
    Lungo.Router.section("main");
    mapOptions = {
      center: latlng,
      zoom: 15,
      mapTypeId: google.maps.MapTypeId.SATELLITE
    };
    map = new google.maps.Map(document.getElementById("map"), mapOptions);
    marker = new google.maps.Marker({
      position: latlng,
      map: map,
      icon: "http://maps.google.com/intl/en_us/mapfiles/ms/micons/blue.png"
    });
    return Lungo.Notification.hide();
  };

  MainCtrl.prototype.onLocate = function() {
    /*do Lungo.Notification.show
    		getLocation = ->
    			if navigator.geolocation
    				navigator.geolocation.getCurrentPosition bien
    			else
    				Lungo.Notification.error "Error al tratar de ubicarte", 3	
    
    		bien = (position) -> 
    			x = document.getElementById("map")
    			console.log position
    			coordenadas = new google.maps.LatLng(position.coords.latitude, position.coords.longitude)
    			mapOptions =
    			    zoom: 15
    			    center: coordenadas
    			    mapTypeControl: true
    			    navigationControlOptions:
    			        style: google.maps.NavigationControlStyle.SMALL
    			    mapTypeId: google.maps.MapTypeId.SATELLITE
    
    			map = new google.maps.Map(x, mapOptions)
    			marker = new google.maps.Marker
    		     position: coordenadas
    	         icon: "http://maps.google.com/intl/en_us/mapfiles/ms/micons/blue.png"
    	         map: map
    		Lungo.Router.section "main"
    		do Lungo.Notification.hide
    */

  };

  MainCtrl.prototype.onfood = function() {
    return $.ajax({
      url: "http://www.pideloya.co/get_venues.json",
      type: "GET",
      dataType: "json",
      success: function(data) {
        var venues;
        console.log(data["venues"][0]["name"]);
        venues = data["venues"];
        return $.each(venues, function(index, value) {
          return map.addMarker({
            lat: venues[index]["latitude"],
            lng: venues[index]["longitude"]
          });
        });
      },
      error: function(data, status, errorThrown) {
        console.log(data);
        console.log(status);
        return console.log(errorThrown);
      }
    });
  };

  return MainCtrl;

})(Monocle.Controller);

__Controller.Main = new MainCtrl("section#main");
