// Generated by CoffeeScript 1.6.2
var SingupCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

SingupCtrl = (function(_super) {
  __extends(SingupCtrl, _super);

  function SingupCtrl() {
    _ref = SingupCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  SingupCtrl.prototype.elements = {
    "#txtUsername": "user",
    "#txtEmail": "email",
    "#txtPass": "password"
  };

  SingupCtrl.prototype.events = {
    "tap a[data-action=singup]": "onSingup",
    "tap a[data-action=login]": "onLogin"
  };

  SingupCtrl.prototype.onSingup = function(e) {
    var user,
      _this = this;

    Lungo.Notification.show();
    if (this.user.val() && this.email.val() && this.password.val()) {
      user = new Parse.User();
      user.set("username", this.user.val());
      user.set("email", this.email.val());
      user.set("password", this.password.val());
      user.signUp().then(function(object, error) {
        if (error) {
          return Lungo.Notification.error(error.message, "user", "user", 3);
        } else {
          _this.user.val("");
          _this.email.val("");
          _this.password.val("");
          return Lungo.Router.back();
        }
      });
    } else {
      Lungo.Notification.error("Por favor llene todos los campos", "Para registrase necesitas llenar todos los campos correctamente", "warning-sign", 5);
    }
    return Lungo.Notification.hide();
  };

  SingupCtrl.prototype.onLogin = function(e) {
    return Lungo.Router.section("login");
  };

  return SingupCtrl;

})(Monocle.Controller);

__Controller.Singup = new SingupCtrl("section#sect_singup");
