// Generated by CoffeeScript 1.6.2
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

__View.Asignature = (function(_super) {
  __extends(Asignature, _super);

  function Asignature() {
    _ref = Asignature.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Asignature.prototype.container = "section#main article#art_main ul";

  Asignature.prototype.template = "<li>\n            <div class=\"right bubble orange\">{{semester}} semestre</div>\n	<strong>{{name}}</strong>\n</li>";

  return Asignature;

})(Monocle.View);
