// Generated by CoffeeScript 1.6.2
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

__View.UserConfig = (function(_super) {
  __extends(UserConfig, _super);

  function UserConfig() {
    _ref = UserConfig.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return UserConfig;

})(Monocle.View);
